// Mocks generated by Mockito 5.4.6 from annotations
// in smarthealth_shep/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:smarthealth_shep/core/network/api_service.dart' as _i2;
import 'package:smarthealth_shep/features/home/data/home_repository.dart'
    as _i5;
import 'package:smarthealth_shep/shared/data/category_repository.dart' as _i15;
import 'package:smarthealth_shep/shared/data/local/provider_dao.dart' as _i6;
import 'package:smarthealth_shep/shared/data/sync/sync_queue_item.dart' as _i4;
import 'package:smarthealth_shep/shared/data/sync/sync_queue_storage.dart'
    as _i3;
import 'package:smarthealth_shep/shared/data/sync/sync_service.dart' as _i14;
import 'package:smarthealth_shep/shared/models/category_model.dart' as _i16;
import 'package:smarthealth_shep/shared/models/facility_model.dart' as _i12;
import 'package:smarthealth_shep/shared/models/facility_public_profile.dart'
    as _i13;
import 'package:smarthealth_shep/shared/models/provider_model.dart' as _i8;
import 'package:smarthealth_shep/shared/models/provider_search_filter.dart'
    as _i9;
import 'package:smarthealth_shep/shared/models/service_category_model.dart'
    as _i17;
import 'package:smarthealth_shep/shared/models/specialty_model.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProviderSyncPayload_0 extends _i1.SmartFake
    implements _i2.ProviderSyncPayload {
  _FakeProviderSyncPayload_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncQueueStorage_1 extends _i1.SmartFake
    implements _i3.SyncQueueStorage {
  _FakeSyncQueueStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncRunResult_2 extends _i1.SmartFake implements _i4.SyncRunResult {
  _FakeSyncRunResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeSyncResult_3 extends _i1.SmartFake
    implements _i5.HomeSyncResult {
  _FakeHomeSyncResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProviderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockProviderDao extends _i1.Mock implements _i6.ProviderDao {
  MockProviderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<DateTime?> getLastSync() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSync, []),
            returnValue: _i7.Future<DateTime?>.value(),
          )
          as _i7.Future<DateTime?>);

  @override
  _i7.Future<void> setLastSync(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSync, [timestamp]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> isStale(String? id, {Duration? maxAge}) =>
      (super.noSuchMethod(
            Invocation.method(#isStale, [id], {#maxAge: maxAge}),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i8.ProviderModel?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i7.Future<_i8.ProviderModel?>.value(),
          )
          as _i7.Future<_i8.ProviderModel?>);

  @override
  _i7.Future<List<_i8.ProviderModel>> getAll({String? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#categoryId: categoryId}),
            returnValue: _i7.Future<List<_i8.ProviderModel>>.value(
              <_i8.ProviderModel>[],
            ),
          )
          as _i7.Future<List<_i8.ProviderModel>>);

  @override
  _i7.Future<List<_i8.ProviderModel>> getNearby(
    double? lat,
    double? lon,
    double? radiusKm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNearby, [lat, lon, radiusKm]),
            returnValue: _i7.Future<List<_i8.ProviderModel>>.value(
              <_i8.ProviderModel>[],
            ),
          )
          as _i7.Future<List<_i8.ProviderModel>>);

  @override
  _i7.Future<List<_i8.ProviderModel>> search(
    _i9.ProviderSearchFilter? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#search, [filter]),
            returnValue: _i7.Future<List<_i8.ProviderModel>>.value(
              <_i8.ProviderModel>[],
            ),
          )
          as _i7.Future<List<_i8.ProviderModel>>);

  @override
  _i7.Future<void> upsertProvider(_i8.ProviderModel? provider) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProvider, [provider]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> upsertProviders(List<_i8.ProviderModel>? providers) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProviders, [providers]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProviders(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProviders, [ids]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i7.Future<List<_i8.ProviderModel>> fetchNearbyProviders({
    required double? lat,
    required double? lon,
    required double? radiusKm,
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNearbyProviders, [], {
              #lat: lat,
              #lon: lon,
              #radiusKm: radiusKm,
              #since: since,
            }),
            returnValue: _i7.Future<List<_i8.ProviderModel>>.value(
              <_i8.ProviderModel>[],
            ),
          )
          as _i7.Future<List<_i8.ProviderModel>>);

  @override
  _i7.Future<List<_i8.ProviderModel>> searchProviders(
    _i9.ProviderSearchFilter? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchProviders, [filter]),
            returnValue: _i7.Future<List<_i8.ProviderModel>>.value(
              <_i8.ProviderModel>[],
            ),
          )
          as _i7.Future<List<_i8.ProviderModel>>);

  @override
  _i7.Future<_i8.ProviderModel?> getProviderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProviderById, [id]),
            returnValue: _i7.Future<_i8.ProviderModel?>.value(),
          )
          as _i7.Future<_i8.ProviderModel?>);

  @override
  _i7.Future<List<({int count, String facilityType, String label})>>
  fetchFacilityTypeCatalog() =>
      (super.noSuchMethod(
            Invocation.method(#fetchFacilityTypeCatalog, []),
            returnValue:
                _i7.Future<
                  List<({int count, String facilityType, String label})>
                >.value(<({int count, String facilityType, String label})>[]),
          )
          as _i7.Future<
            List<({int count, String facilityType, String label})>
          >);

  @override
  _i7.Future<List<_i11.SpecialtyModel>> fetchCatalogSpecialties({
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCatalogSpecialties, [], {#limit: limit}),
            returnValue: _i7.Future<List<_i11.SpecialtyModel>>.value(
              <_i11.SpecialtyModel>[],
            ),
          )
          as _i7.Future<List<_i11.SpecialtyModel>>);

  @override
  _i7.Future<List<({String id, String label})>> fetchCatalogConditions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCatalogConditions, []),
            returnValue: _i7.Future<List<({String id, String label})>>.value(
              <({String id, String label})>[],
            ),
          )
          as _i7.Future<List<({String id, String label})>>);

  @override
  _i7.Future<List<({String id, String label})>> fetchCatalogAgeGroups() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCatalogAgeGroups, []),
            returnValue: _i7.Future<List<({String id, String label})>>.value(
              <({String id, String label})>[],
            ),
          )
          as _i7.Future<List<({String id, String label})>>);

  @override
  _i7.Future<List<_i12.FacilityModel>> searchFacilities(
    _i9.ProviderSearchFilter? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchFacilities, [filter]),
            returnValue: _i7.Future<List<_i12.FacilityModel>>.value(
              <_i12.FacilityModel>[],
            ),
          )
          as _i7.Future<List<_i12.FacilityModel>>);

  @override
  _i7.Future<List<_i12.FacilityModel>> fetchNearbyFacilities({
    required double? lat,
    required double? lon,
    required double? radiusKm,
    int? limit = 50,
    int? page = 1,
    String? facilityType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNearbyFacilities, [], {
              #lat: lat,
              #lon: lon,
              #radiusKm: radiusKm,
              #limit: limit,
              #page: page,
              #facilityType: facilityType,
            }),
            returnValue: _i7.Future<List<_i12.FacilityModel>>.value(
              <_i12.FacilityModel>[],
            ),
          )
          as _i7.Future<List<_i12.FacilityModel>>);

  @override
  _i7.Future<List<_i12.FacilityModel>> fetchFacilitiesByCity({
    required String? city,
    String? facilityType,
    int? limit = 50,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFacilitiesByCity, [], {
              #city: city,
              #facilityType: facilityType,
              #limit: limit,
              #page: page,
            }),
            returnValue: _i7.Future<List<_i12.FacilityModel>>.value(
              <_i12.FacilityModel>[],
            ),
          )
          as _i7.Future<List<_i12.FacilityModel>>);

  @override
  _i7.Future<_i12.FacilityModel?> getFacilityById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilityById, [id]),
            returnValue: _i7.Future<_i12.FacilityModel?>.value(),
          )
          as _i7.Future<_i12.FacilityModel?>);

  @override
  _i7.Future<_i13.FacilityPublicProfile?> fetchFacilityPublicProfile(
    String? id, {
    double? distanceKm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchFacilityPublicProfile,
              [id],
              {#distanceKm: distanceKm},
            ),
            returnValue: _i7.Future<_i13.FacilityPublicProfile?>.value(),
          )
          as _i7.Future<_i13.FacilityPublicProfile?>);

  @override
  _i7.Future<List<_i13.FacilitySpecialistSummary>> fetchFacilitySpecialists(
    String? facilityId, {
    int? limit = 5,
    String? serviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchFacilitySpecialists,
              [facilityId],
              {#limit: limit, #serviceId: serviceId},
            ),
            returnValue: _i7.Future<List<_i13.FacilitySpecialistSummary>>.value(
              <_i13.FacilitySpecialistSummary>[],
            ),
          )
          as _i7.Future<List<_i13.FacilitySpecialistSummary>>);

  @override
  _i7.Future<List<_i13.FacilityAvailabilityDay>> fetchFacilityAvailability(
    String? facilityId, {
    String? serviceId,
    int? days = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchFacilityAvailability,
              [facilityId],
              {#serviceId: serviceId, #days: days},
            ),
            returnValue: _i7.Future<List<_i13.FacilityAvailabilityDay>>.value(
              <_i13.FacilityAvailabilityDay>[],
            ),
          )
          as _i7.Future<List<_i13.FacilityAvailabilityDay>>);

  @override
  _i7.Future<_i2.ProviderSyncPayload> syncProviders({DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#syncProviders, [], {#since: since}),
            returnValue: _i7.Future<_i2.ProviderSyncPayload>.value(
              _FakeProviderSyncPayload_0(
                this,
                Invocation.method(#syncProviders, [], {#since: since}),
              ),
            ),
          )
          as _i7.Future<_i2.ProviderSyncPayload>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i14.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SyncQueueStorage get queueStorage =>
      (super.noSuchMethod(
            Invocation.getter(#queueStorage),
            returnValue: _FakeSyncQueueStorage_1(
              this,
              Invocation.getter(#queueStorage),
            ),
          )
          as _i3.SyncQueueStorage);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> isOnline() =>
      (super.noSuchMethod(
            Invocation.method(#isOnline, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> enqueue({
    required _i4.SyncMutationType? mutationType,
    required _i4.SyncEntityType? entityType,
    required String? entityId,
    required Map<String, dynamic>? payload,
    DateTime? clientUpdatedAt,
    bool? optimistic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #mutationType: mutationType,
              #entityType: entityType,
              #entityId: entityId,
              #payload: payload,
              #clientUpdatedAt: clientUpdatedAt,
              #optimistic: optimistic,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.SyncRunResult> syncPullToRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#syncPullToRefresh, []),
            returnValue: _i7.Future<_i4.SyncRunResult>.value(
              _FakeSyncRunResult_2(
                this,
                Invocation.method(#syncPullToRefresh, []),
              ),
            ),
          )
          as _i7.Future<_i4.SyncRunResult>);

  @override
  _i7.Future<_i4.SyncRunResult> runBackgroundSync() =>
      (super.noSuchMethod(
            Invocation.method(#runBackgroundSync, []),
            returnValue: _i7.Future<_i4.SyncRunResult>.value(
              _FakeSyncRunResult_2(
                this,
                Invocation.method(#runBackgroundSync, []),
              ),
            ),
          )
          as _i7.Future<_i4.SyncRunResult>);

  @override
  _i7.Future<_i4.SyncRunResult> syncNow({
    _i14.SyncTrigger? trigger = _i14.SyncTrigger.manual,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncNow, [], {#trigger: trigger}),
            returnValue: _i7.Future<_i4.SyncRunResult>.value(
              _FakeSyncRunResult_2(
                this,
                Invocation.method(#syncNow, [], {#trigger: trigger}),
              ),
            ),
          )
          as _i7.Future<_i4.SyncRunResult>);

  @override
  _i7.Future<List<_i4.SyncQueueItem>> pendingItems() =>
      (super.noSuchMethod(
            Invocation.method(#pendingItems, []),
            returnValue: _i7.Future<List<_i4.SyncQueueItem>>.value(
              <_i4.SyncQueueItem>[],
            ),
          )
          as _i7.Future<List<_i4.SyncQueueItem>>);

  @override
  _i7.Future<List<_i4.SyncQueueItem>> manualRetryItems() =>
      (super.noSuchMethod(
            Invocation.method(#manualRetryItems, []),
            returnValue: _i7.Future<List<_i4.SyncQueueItem>>.value(
              <_i4.SyncQueueItem>[],
            ),
          )
          as _i7.Future<List<_i4.SyncQueueItem>>);

  @override
  _i7.Future<int> pendingCount() =>
      (super.noSuchMethod(
            Invocation.method(#pendingCount, []),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<_i4.SyncRunResult> retryManualItems() =>
      (super.noSuchMethod(
            Invocation.method(#retryManualItems, []),
            returnValue: _i7.Future<_i4.SyncRunResult>.value(
              _FakeSyncRunResult_2(
                this,
                Invocation.method(#retryManualItems, []),
              ),
            ),
          )
          as _i7.Future<_i4.SyncRunResult>);

  @override
  void schedule(String? key, _i7.Future<void> Function()? task) =>
      super.noSuchMethod(
        Invocation.method(#schedule, [key, task]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i5.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.HomeSyncResult> sync({
    bool? forceRefresh = false,
    String? facilityType,
    bool? refreshOrigin = false,
    String? manualCityName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sync, [], {
              #forceRefresh: forceRefresh,
              #facilityType: facilityType,
              #refreshOrigin: refreshOrigin,
              #manualCityName: manualCityName,
            }),
            returnValue: _i7.Future<_i5.HomeSyncResult>.value(
              _FakeHomeSyncResult_3(
                this,
                Invocation.method(#sync, [], {
                  #forceRefresh: forceRefresh,
                  #facilityType: facilityType,
                  #refreshOrigin: refreshOrigin,
                  #manualCityName: manualCityName,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.HomeSyncResult>);

  @override
  _i7.Future<_i5.HomeSyncResult> syncCityFallback({
    required String? city,
    String? facilityType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncCityFallback, [], {
              #city: city,
              #facilityType: facilityType,
            }),
            returnValue: _i7.Future<_i5.HomeSyncResult>.value(
              _FakeHomeSyncResult_3(
                this,
                Invocation.method(#syncCityFallback, [], {
                  #city: city,
                  #facilityType: facilityType,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.HomeSyncResult>);

  @override
  _i7.Future<void> saveCity(String? city, {bool? manual = false}) =>
      (super.noSuchMethod(
            Invocation.method(#saveCity, [city], {#manual: manual}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i15.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i16.CategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i7.Future<List<_i16.CategoryModel>>.value(
              <_i16.CategoryModel>[],
            ),
          )
          as _i7.Future<List<_i16.CategoryModel>>);

  @override
  _i7.Future<List<_i17.ServiceCategoryModel>> getHomeServiceCategories({
    String? nearMeLabel = 'Near Me',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeServiceCategories, [], {
              #nearMeLabel: nearMeLabel,
            }),
            returnValue: _i7.Future<List<_i17.ServiceCategoryModel>>.value(
              <_i17.ServiceCategoryModel>[],
            ),
          )
          as _i7.Future<List<_i17.ServiceCategoryModel>>);
}
