// Mocks generated by Mockito 5.4.6 from annotations
// in smarthealth_shep/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:smarthealth_shep/core/network/api_service.dart' as _i2;
import 'package:smarthealth_shep/shared/data/local/provider_dao.dart' as _i5;
import 'package:smarthealth_shep/shared/data/sync/sync_queue_item.dart' as _i4;
import 'package:smarthealth_shep/shared/data/sync/sync_queue_storage.dart'
    as _i3;
import 'package:smarthealth_shep/shared/data/sync/sync_service.dart' as _i10;
import 'package:smarthealth_shep/shared/models/provider_model.dart' as _i7;
import 'package:smarthealth_shep/shared/models/provider_search_filter.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProviderSyncPayload_0 extends _i1.SmartFake
    implements _i2.ProviderSyncPayload {
  _FakeProviderSyncPayload_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncQueueStorage_1 extends _i1.SmartFake
    implements _i3.SyncQueueStorage {
  _FakeSyncQueueStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncRunResult_2 extends _i1.SmartFake implements _i4.SyncRunResult {
  _FakeSyncRunResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProviderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockProviderDao extends _i1.Mock implements _i5.ProviderDao {
  MockProviderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<DateTime?> getLastSync() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSync, []),
            returnValue: _i6.Future<DateTime?>.value(),
          )
          as _i6.Future<DateTime?>);

  @override
  _i6.Future<void> setLastSync(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSync, [timestamp]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isStale(String? id, {Duration? maxAge}) =>
      (super.noSuchMethod(
            Invocation.method(#isStale, [id], {#maxAge: maxAge}),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i7.ProviderModel?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i7.ProviderModel?>.value(),
          )
          as _i6.Future<_i7.ProviderModel?>);

  @override
  _i6.Future<List<_i7.ProviderModel>> getAll({String? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#categoryId: categoryId}),
            returnValue: _i6.Future<List<_i7.ProviderModel>>.value(
              <_i7.ProviderModel>[],
            ),
          )
          as _i6.Future<List<_i7.ProviderModel>>);

  @override
  _i6.Future<List<_i7.ProviderModel>> getNearby(
    double? lat,
    double? lon,
    double? radiusKm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNearby, [lat, lon, radiusKm]),
            returnValue: _i6.Future<List<_i7.ProviderModel>>.value(
              <_i7.ProviderModel>[],
            ),
          )
          as _i6.Future<List<_i7.ProviderModel>>);

  @override
  _i6.Future<List<_i7.ProviderModel>> search(
    _i8.ProviderSearchFilter? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#search, [filter]),
            returnValue: _i6.Future<List<_i7.ProviderModel>>.value(
              <_i7.ProviderModel>[],
            ),
          )
          as _i6.Future<List<_i7.ProviderModel>>);

  @override
  _i6.Future<void> upsertProvider(_i7.ProviderModel? provider) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProvider, [provider]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> upsertProviders(List<_i7.ProviderModel>? providers) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProviders, [providers]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteProviders(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProviders, [ids]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.Future<List<_i7.ProviderModel>> fetchNearbyProviders({
    required double? lat,
    required double? lon,
    required double? radiusKm,
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNearbyProviders, [], {
              #lat: lat,
              #lon: lon,
              #radiusKm: radiusKm,
              #since: since,
            }),
            returnValue: _i6.Future<List<_i7.ProviderModel>>.value(
              <_i7.ProviderModel>[],
            ),
          )
          as _i6.Future<List<_i7.ProviderModel>>);

  @override
  _i6.Future<List<_i7.ProviderModel>> searchProviders(
    _i8.ProviderSearchFilter? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchProviders, [filter]),
            returnValue: _i6.Future<List<_i7.ProviderModel>>.value(
              <_i7.ProviderModel>[],
            ),
          )
          as _i6.Future<List<_i7.ProviderModel>>);

  @override
  _i6.Future<_i7.ProviderModel?> getProviderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProviderById, [id]),
            returnValue: _i6.Future<_i7.ProviderModel?>.value(),
          )
          as _i6.Future<_i7.ProviderModel?>);

  @override
  _i6.Future<_i2.ProviderSyncPayload> syncProviders({DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#syncProviders, [], {#since: since}),
            returnValue: _i6.Future<_i2.ProviderSyncPayload>.value(
              _FakeProviderSyncPayload_0(
                this,
                Invocation.method(#syncProviders, [], {#since: since}),
              ),
            ),
          )
          as _i6.Future<_i2.ProviderSyncPayload>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i10.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SyncQueueStorage get queueStorage =>
      (super.noSuchMethod(
            Invocation.getter(#queueStorage),
            returnValue: _FakeSyncQueueStorage_1(
              this,
              Invocation.getter(#queueStorage),
            ),
          )
          as _i3.SyncQueueStorage);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> isOnline() =>
      (super.noSuchMethod(
            Invocation.method(#isOnline, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> enqueue({
    required _i4.SyncMutationType? mutationType,
    required _i4.SyncEntityType? entityType,
    required String? entityId,
    required Map<String, dynamic>? payload,
    DateTime? clientUpdatedAt,
    bool? optimistic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #mutationType: mutationType,
              #entityType: entityType,
              #entityId: entityId,
              #payload: payload,
              #clientUpdatedAt: clientUpdatedAt,
              #optimistic: optimistic,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.SyncRunResult> syncPullToRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#syncPullToRefresh, []),
            returnValue: _i6.Future<_i4.SyncRunResult>.value(
              _FakeSyncRunResult_2(
                this,
                Invocation.method(#syncPullToRefresh, []),
              ),
            ),
          )
          as _i6.Future<_i4.SyncRunResult>);

  @override
  _i6.Future<_i4.SyncRunResult> runBackgroundSync() =>
      (super.noSuchMethod(
            Invocation.method(#runBackgroundSync, []),
            returnValue: _i6.Future<_i4.SyncRunResult>.value(
              _FakeSyncRunResult_2(
                this,
                Invocation.method(#runBackgroundSync, []),
              ),
            ),
          )
          as _i6.Future<_i4.SyncRunResult>);

  @override
  _i6.Future<_i4.SyncRunResult> syncNow({
    _i10.SyncTrigger? trigger = _i10.SyncTrigger.manual,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncNow, [], {#trigger: trigger}),
            returnValue: _i6.Future<_i4.SyncRunResult>.value(
              _FakeSyncRunResult_2(
                this,
                Invocation.method(#syncNow, [], {#trigger: trigger}),
              ),
            ),
          )
          as _i6.Future<_i4.SyncRunResult>);

  @override
  _i6.Future<List<_i4.SyncQueueItem>> pendingItems() =>
      (super.noSuchMethod(
            Invocation.method(#pendingItems, []),
            returnValue: _i6.Future<List<_i4.SyncQueueItem>>.value(
              <_i4.SyncQueueItem>[],
            ),
          )
          as _i6.Future<List<_i4.SyncQueueItem>>);

  @override
  _i6.Future<List<_i4.SyncQueueItem>> manualRetryItems() =>
      (super.noSuchMethod(
            Invocation.method(#manualRetryItems, []),
            returnValue: _i6.Future<List<_i4.SyncQueueItem>>.value(
              <_i4.SyncQueueItem>[],
            ),
          )
          as _i6.Future<List<_i4.SyncQueueItem>>);

  @override
  _i6.Future<int> pendingCount() =>
      (super.noSuchMethod(
            Invocation.method(#pendingCount, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i4.SyncRunResult> retryManualItems() =>
      (super.noSuchMethod(
            Invocation.method(#retryManualItems, []),
            returnValue: _i6.Future<_i4.SyncRunResult>.value(
              _FakeSyncRunResult_2(
                this,
                Invocation.method(#retryManualItems, []),
              ),
            ),
          )
          as _i6.Future<_i4.SyncRunResult>);

  @override
  void schedule(String? key, _i6.Future<void> Function()? task) =>
      super.noSuchMethod(
        Invocation.method(#schedule, [key, task]),
        returnValueForMissingStub: null,
      );
}
