// Mocks generated by Mockito 5.4.6 from annotations
// in smarthealth_shep/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:smarthealth_shep/core/network/api_service.dart' as _i2;
import 'package:smarthealth_shep/shared/data/local/provider_dao.dart' as _i4;
import 'package:smarthealth_shep/shared/data/sync/sync_queue_item.dart' as _i3;
import 'package:smarthealth_shep/shared/data/sync/sync_service.dart' as _i9;
import 'package:smarthealth_shep/shared/models/provider_model.dart' as _i6;
import 'package:smarthealth_shep/shared/models/provider_search_filter.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProviderSyncPayload_0 extends _i1.SmartFake
    implements _i2.ProviderSyncPayload {
  _FakeProviderSyncPayload_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncRunResult_1 extends _i1.SmartFake implements _i3.SyncRunResult {
  _FakeSyncRunResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProviderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockProviderDao extends _i1.Mock implements _i4.ProviderDao {
  MockProviderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<DateTime?> getLastSync() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSync, []),
            returnValue: _i5.Future<DateTime?>.value(),
          )
          as _i5.Future<DateTime?>);

  @override
  _i5.Future<void> setLastSync(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSync, [timestamp]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isStale(String? id, {Duration? maxAge}) =>
      (super.noSuchMethod(
            Invocation.method(#isStale, [id], {#maxAge: maxAge}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i6.ProviderModel?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i6.ProviderModel?>.value(),
          )
          as _i5.Future<_i6.ProviderModel?>);

  @override
  _i5.Future<List<_i6.ProviderModel>> getAll({String? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#categoryId: categoryId}),
            returnValue: _i5.Future<List<_i6.ProviderModel>>.value(
              <_i6.ProviderModel>[],
            ),
          )
          as _i5.Future<List<_i6.ProviderModel>>);

  @override
  _i5.Future<List<_i6.ProviderModel>> getNearby(
    double? lat,
    double? lon,
    double? radiusKm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNearby, [lat, lon, radiusKm]),
            returnValue: _i5.Future<List<_i6.ProviderModel>>.value(
              <_i6.ProviderModel>[],
            ),
          )
          as _i5.Future<List<_i6.ProviderModel>>);

  @override
  _i5.Future<List<_i6.ProviderModel>> search(
    _i7.ProviderSearchFilter? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#search, [filter]),
            returnValue: _i5.Future<List<_i6.ProviderModel>>.value(
              <_i6.ProviderModel>[],
            ),
          )
          as _i5.Future<List<_i6.ProviderModel>>);

  @override
  _i5.Future<void> upsertProvider(_i6.ProviderModel? provider) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProvider, [provider]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertProviders(List<_i6.ProviderModel>? providers) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProviders, [providers]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProviders(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProviders, [ids]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i5.Future<List<_i6.ProviderModel>> fetchNearbyProviders({
    required double? lat,
    required double? lon,
    required double? radiusKm,
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNearbyProviders, [], {
              #lat: lat,
              #lon: lon,
              #radiusKm: radiusKm,
              #since: since,
            }),
            returnValue: _i5.Future<List<_i6.ProviderModel>>.value(
              <_i6.ProviderModel>[],
            ),
          )
          as _i5.Future<List<_i6.ProviderModel>>);

  @override
  _i5.Future<List<_i6.ProviderModel>> searchProviders(
    _i7.ProviderSearchFilter? filter, {
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProviders, [filter], {#since: since}),
            returnValue: _i5.Future<List<_i6.ProviderModel>>.value(
              <_i6.ProviderModel>[],
            ),
          )
          as _i5.Future<List<_i6.ProviderModel>>);

  @override
  _i5.Future<_i6.ProviderModel?> getProviderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProviderById, [id]),
            returnValue: _i5.Future<_i6.ProviderModel?>.value(),
          )
          as _i5.Future<_i6.ProviderModel?>);

  @override
  _i5.Future<_i2.ProviderSyncPayload> syncProviders({DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#syncProviders, [], {#since: since}),
            returnValue: _i5.Future<_i2.ProviderSyncPayload>.value(
              _FakeProviderSyncPayload_0(
                this,
                Invocation.method(#syncProviders, [], {#since: since}),
              ),
            ),
          )
          as _i5.Future<_i2.ProviderSyncPayload>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i9.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> isOnline() =>
      (super.noSuchMethod(
            Invocation.method(#isOnline, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> enqueue({
    required _i3.SyncMutationType? mutationType,
    required _i3.SyncEntityType? entityType,
    required String? entityId,
    required Map<String, dynamic>? payload,
    DateTime? clientUpdatedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #mutationType: mutationType,
              #entityType: entityType,
              #entityId: entityId,
              #payload: payload,
              #clientUpdatedAt: clientUpdatedAt,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.SyncRunResult> syncPullToRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#syncPullToRefresh, []),
            returnValue: _i5.Future<_i3.SyncRunResult>.value(
              _FakeSyncRunResult_1(
                this,
                Invocation.method(#syncPullToRefresh, []),
              ),
            ),
          )
          as _i5.Future<_i3.SyncRunResult>);

  @override
  _i5.Future<_i3.SyncRunResult> runBackgroundSync() =>
      (super.noSuchMethod(
            Invocation.method(#runBackgroundSync, []),
            returnValue: _i5.Future<_i3.SyncRunResult>.value(
              _FakeSyncRunResult_1(
                this,
                Invocation.method(#runBackgroundSync, []),
              ),
            ),
          )
          as _i5.Future<_i3.SyncRunResult>);

  @override
  _i5.Future<_i3.SyncRunResult> syncNow({
    _i9.SyncTrigger? trigger = _i9.SyncTrigger.manual,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncNow, [], {#trigger: trigger}),
            returnValue: _i5.Future<_i3.SyncRunResult>.value(
              _FakeSyncRunResult_1(
                this,
                Invocation.method(#syncNow, [], {#trigger: trigger}),
              ),
            ),
          )
          as _i5.Future<_i3.SyncRunResult>);

  @override
  _i5.Future<List<_i3.SyncQueueItem>> pendingItems() =>
      (super.noSuchMethod(
            Invocation.method(#pendingItems, []),
            returnValue: _i5.Future<List<_i3.SyncQueueItem>>.value(
              <_i3.SyncQueueItem>[],
            ),
          )
          as _i5.Future<List<_i3.SyncQueueItem>>);

  @override
  _i5.Future<List<_i3.SyncQueueItem>> manualRetryItems() =>
      (super.noSuchMethod(
            Invocation.method(#manualRetryItems, []),
            returnValue: _i5.Future<List<_i3.SyncQueueItem>>.value(
              <_i3.SyncQueueItem>[],
            ),
          )
          as _i5.Future<List<_i3.SyncQueueItem>>);

  @override
  _i5.Future<int> pendingCount() =>
      (super.noSuchMethod(
            Invocation.method(#pendingCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.SyncRunResult> retryManualItems() =>
      (super.noSuchMethod(
            Invocation.method(#retryManualItems, []),
            returnValue: _i5.Future<_i3.SyncRunResult>.value(
              _FakeSyncRunResult_1(
                this,
                Invocation.method(#retryManualItems, []),
              ),
            ),
          )
          as _i5.Future<_i3.SyncRunResult>);

  @override
  void schedule(String? key, _i5.Future<void> Function()? task) =>
      super.noSuchMethod(
        Invocation.method(#schedule, [key, task]),
        returnValueForMissingStub: null,
      );
}
