global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: smarthealth-api
    metrics_path: /metrics
    static_configs:
      - targets: ["smarthealth-api:3000"]
        labels:
          service: api

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: postgres

  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: redis

  - job_name: nginx
    static_configs:
      - targets: ["nginx:80"]
        labels:
          service: nginx
    metrics_path: /health
